import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Pencil, Download, Trash2 } from "lucide-react";
import { api, downloadApiFile } from "../../api/client";
import type { CalculatorQuote } from "../../features/calculadora/model";
import { buildQuotePdf } from "../../features/calculadora/pdf";
import { useFeedback } from "../../context/FeedbackContext";
export default function CalculadoraHistorial(){
 const [items,setItems]=useState<CalculatorQuote[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(true);const [search,setSearch]=useState("");const [date,setDate]=useState("");const [kind,setKind]=useState("todos");const [order,setOrder]=useState("desc");const feedback=useFeedback();
 useEffect(()=>{api.get<CalculatorQuote[]>("/api/cotizador").then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 async function download(q:CalculatorQuote){try{if(q.archivo_pdf)await downloadApiFile(q.archivo_pdf);else(await buildQuotePdf(q)).save(`${q.numero}.pdf`);}catch(e){setError(e instanceof Error?e.message:"No se pudo descargar.");}}
 async function remove(q:CalculatorQuote){if(!(await feedback.confirm({title:"Eliminar prueba",message:"Esta prueba se eliminará del historial.",confirmLabel:"Eliminar",danger:true})))return;try{await api.delete(`/api/cotizador/${q.id}`);setItems(i=>i.filter(p=>p.id!==q.id));}catch(e){setError(e instanceof Error?e.message:"No se pudo eliminar.");}}
 const visible=items.filter(q=>(kind==="todos"||(kind==="oficiales"?q.oficial:!q.oficial))&&(!date||q.creado_en?.slice(0,10)===date)&&`${q.numero} ${q.cliente_nombre} ${q.cliente_documento}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>order==="asc"?(a.id??0)-(b.id??0):(b.id??0)-(a.id??0));
 return <div><div className="admin-header-row"><div><h1>Historial de la calculadora</h1><p className="subtitle">Pruebas y versiones guardadas. Las oficiales se identifican y conservan su PDF.</p></div><Link className="btn-admin yellow" to="/admin/calculadora">Nueva cotización</Link></div>{error&&<p className="admin-error" role="alert">{error}</p>}<div className="admin-filters-bar calculator-history-filters"><label>Buscar<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Fecha<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Tipo<select aria-label="Tipo" value={kind} onChange={e=>setKind(e.target.value)}><option value="todos">Todas</option><option value="pruebas">Pruebas</option><option value="oficiales">Oficiales</option></select></label><label>Orden<select aria-label="Orden" value={order} onChange={e=>setOrder(e.target.value)}><option value="desc">Más recientes primero</option><option value="asc">Más antiguas primero</option></select></label></div>{loading?<p>Cargando historial…</p>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Número</th><th>Cliente</th><th>Fecha</th><th>Tipo</th><th>Total</th><th>Acciones</th></tr></thead><tbody>{visible.map(q=><tr key={q.id}><td>{q.numero}</td><td>{q.cliente_nombre}</td><td>{q.creado_en}</td><td><span className={`featured-status ${q.oficial?"is-featured":""}`}>{q.oficial?"Oficial":"Prueba"}</span></td><td>{q.moneda_mostrar} {Number(q.total).toFixed(2)}</td><td className="calculator-history-actions"><Link className="access-icon-action" title="Crear una copia editable; se conservará la versión original" data-tooltip="Crear una copia editable; se conservará la versión original" aria-label={`Editar ${q.numero}`} to={`/admin/calculadora?historial=${q.id}`}><Pencil size={16}/></Link> <button className="access-icon-action" title="Descargar PDF" data-tooltip="Descargar PDF" aria-label={`Descargar ${q.numero}`} onClick={()=>void download(q)}><Download size={16}/></button> {!q.oficial&&<button className="access-icon-action danger" title="Eliminar esta prueba del historial; las oficiales se conservan" data-tooltip="Eliminar esta prueba del historial; las oficiales se conservan" aria-label={`Eliminar ${q.numero}`} onClick={()=>void remove(q)}><Trash2 size={16}/></button>} {q.cotizacion_id&&<Link to={`/admin/cotizaciones/${q.cotizacion_id}`}>Ver oficial</Link>}</td></tr>)}</tbody></table>{!visible.length&&<p className="calculator-history-empty">No hay documentos en este filtro.</p>}</div>}</div>;
}
