import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { Plus, Trash2, Pencil, Save, Download, History } from "lucide-react";
import { api } from "../../api/client";
import { useMaquinarias, useRepuestos } from "../../hooks/useApiData";
import { useFeedback } from "../../context/FeedbackContext";
import { newQuote, newItem, finalPrice, totalQuote, type CalculatorItem, type CalculatorQuote } from "../../features/calculadora/model";
import { buildQuotePdf } from "../../features/calculadora/pdf";
import type { QuoteDetail } from "../../types/content";
import "./Calculadora.css";
interface Source {id:number;nombre_cliente:string;email_cliente:string;telefono_cliente:string;detalle:QuoteDetail;origen:string;}
export default function Calculadora(){
  const [params]=useSearchParams();const [quote,setQuote]=useState(newQuote);const [item,setItem]=useState(newItem);const [editing,setEditing]=useState<number|null>(null);
  const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [pdfUrl,setPdfUrl]=useState("");const [search,setSearch]=useState("");
  const [discount,setDiscount]=useState("");const [adjustment,setAdjustment]=useState("");const feedback=useFeedback();
  const {data:parts,loading:loadingParts,error:partsError}=useRepuestos();const {data:machines,loading:loadingMachines,error:machinesError}=useMaquinarias();
  const sourceId=params.get("solicitud");const historyId=params.get("historial");
  useEffect(()=>{let cancelled=false;
    async function load(){setError("");if(!sourceId&&!historyId)return;setLoading(true);
      try{
        if(historyId){const saved=await api.get<CalculatorQuote>(`/api/cotizador/${historyId}`);if(!cancelled)setQuote({...newQuote(),...saved,...{id:undefined,numero:newQuote().numero,registro_clave:crypto.randomUUID(),oficial:false,solicitud_id:saved.cotizacion_id??saved.solicitud_id},items:saved.items.map(i=>({...newItem(),...i,tipo:i.tipo??"repuesto"}))});}
        else{const [source,rawParts,rawMachines]=await Promise.all([api.get<Source>(`/api/cotizaciones/${sourceId}`),api.get<{id:number;codigo:string;marca:string;unidad:string;nombre:string}[]>("/api/repuestos"),api.get<{id:number;marca:string;nombre:string}[]>("/api/maquinaria")]);if(source.origen==="contacto")throw new Error("Los mensajes de Contacto se atienden desde su bandeja.");
          const items=(source.detalle.productos??[]).map(p=>{
            const machine=p.tipo==="maquinaria";const match=machine?rawMachines.find(m=>m.id===Number(p.id)||m.nombre===p.nombre):rawParts.find(r=>r.id===Number(p.id)||r.codigo===p.codigo||r.nombre===p.nombre);
            return { ...newItem(),product_id:Number(p.id)||match?.id,code:p.codigo||(machine?`MAQ-${match?.id??""}`:(match as {codigo?:string})?.codigo??""),brand:p.marca||match?.marca||"",unit:machine?"UND":(match as {unidad?:string})?.unidad||"UND",desc:p.nombre,qty:Number(p.cantidad)||1,currency:"PEN" as const,tipo:machine?"maquinaria" as const:"repuesto" as const,brandAdjustments:[] };
          });
          if(!cancelled)setQuote({...newQuote(),cliente_nombre:source.nombre_cliente,cliente_email:source.email_cliente,cliente_telefono:source.telefono_cliente??"",cliente_documento:source.detalle.numero_documento??"",solicitud_id:source.id,items});}
      }catch(e){if(!cancelled)setError(e instanceof Error?e.message:"No se pudo cargar.");}finally{if(!cancelled)setLoading(false);}}
    void load();return()=>{cancelled=true;};
  },[sourceId,historyId]);
  useEffect(()=>{let cancelled=false;let url="";const timer=setTimeout(()=>{if(!Number.isFinite(totalQuote(quote)))return;buildQuotePdf(quote).then(doc=>{if(!cancelled){url=URL.createObjectURL(doc.output("blob"));setPdfUrl(url);}}).catch(e=>{if(!cancelled)setError(e.message);});},350);return()=>{cancelled=true;clearTimeout(timer);if(url)URL.revokeObjectURL(url);};},[quote]);
  const catalog=[...parts.map(p=>({id:p.id,code:p.codigo,desc:p.nombre,brand:p.marca,unit:p.unidad,tipo:"repuesto" as const})),...machines.map(m=>({id:m.id,code:`MAQ-${m.id}`,desc:m.nombre,brand:m.marca,unit:"UND",tipo:"maquinaria" as const}))];
  const suggestions=search.trim()?catalog.filter(p=>`${p.code} ${p.desc}`.toLowerCase().includes(search.toLowerCase())).slice(0,8):[];
  const total=totalQuote(quote);const valid=Number.isFinite(total);
  function change<K extends keyof CalculatorQuote>(key:K,value:CalculatorQuote[K]){setQuote(q=>({...q,[key]:value}));}
  function add(){if(!item.desc.trim()||item.qty<=0||item.price<0){setError("Completa la descripción, cantidad y precio del producto.");return;}setError("");setQuote(q=>({...q,items:editing===null?[...q.items,item]:q.items.map((p,i)=>i===editing?item:p)}));setItem(newItem());setEditing(null);setSearch("");}
  function percentage(kind:"discounts"|"brandAdjustments",value:string){const n=Number(value);if(!value||n<0||n>100){setError("El porcentaje debe estar entre 0 y 100.");return;}setItem(p=>({...p,[kind]:[...p[kind],n]}));if(kind==="discounts")setDiscount("");else setAdjustment("");}
  async function save(){if(busy)return;if(!quote.items.length||!valid){setError("Agrega productos e ingresa un tipo de cambio válido si corresponde.");return;}if(quote.oficial&&(!quote.cliente_nombre.trim()||quote.items.some(i=>!i.price))){setError("Para registrar una cotización oficial completa el cliente y todos los precios.");return;}setBusy(true);setError("");
    try{const data={...quote,cliente_nombre:quote.cliente_nombre.trim()||"Prueba sin cliente",total};let body:unknown=data;
      if(quote.oficial){const doc=await buildQuotePdf(data);const form=new FormData();form.append("datos",JSON.stringify(data));form.append("pdf",doc.output("blob"),`${quote.numero}.pdf`);body=form;}
      const saved=await api.post<CalculatorQuote>("/api/cotizador",body);setQuote(q=>({...q,id:saved.id,cotizacion_id:saved.cotizacion_id,archivo_pdf:saved.archivo_pdf}));feedback.success(saved.oficial?"Cotización oficial y PDF registrados en el panel.":"Prueba guardada en el historial. No crea una cotización oficial.");
    }catch(e){setError(e instanceof Error?e.message:"No se pudo guardar.");}finally{setBusy(false);}}
  async function download(){try{(await buildQuotePdf({...quote,total})).save(`${quote.numero}.pdf`);}catch(e){setError(e instanceof Error?e.message:"No se pudo generar el PDF.");}}
  if(loading)return <p>Cargando datos de la cotización…</p>;
  const saved=!!quote.id;
  return <div className="calculator"><div className="admin-header-row"><div><h1>Calculadora de cotizaciones</h1><p className="subtitle">Prepara precios, guarda pruebas y registra una cotización oficial cuando esté lista.</p></div><Link className="btn-admin outline" to="/admin/calculadora/historial"><History size={16}/>Historial</Link></div>
    {error&&<p className="admin-error" role="alert">{error}</p>}{quote.solicitud_id&&<p className="calculator-notice">Datos de la solicitud #{quote.solicitud_id} cargados. Revisa precios y cantidades antes de registrar.<Link to={`/admin/cotizaciones/${quote.solicitud_id}`}> Ver solicitud</Link></p>}
    <div className="calculator-layout"><div><fieldset className="calculator-section" disabled={busy||saved}><legend>Cliente</legend><div className="calculator-grid">{([['cliente_nombre','Cliente'],['cliente_documento','DNI / RUC'],['cliente_direccion','Dirección'],['cliente_email','Correo del cliente'],['cliente_telefono','Teléfono del cliente']] as const).map(([key,label])=><label key={key}>{label}<input type={key==="cliente_email"?"email":"text"} value={quote[key]} onChange={e=>change(key,e.target.value)}/></label>)}</div></fieldset>
    <fieldset className="calculator-section" disabled={busy||saved}><legend>Moneda y conversión</legend><div className="calculator-grid"><label>Moneda de la cotización<select aria-label="Moneda de la cotización" value={quote.moneda_mostrar} onChange={e=>change("moneda_mostrar",e.target.value as "PEN"|"USD")}><option value="PEN">Soles (PEN)</option><option value="USD">Dólares (USD)</option></select></label><label>Tipo de cambio (soles por dólar)<input type="number" min="0" step="0.001" value={quote.tipo_cambio||""} onChange={e=>change("tipo_cambio",Number(e.target.value))}/></label></div><p>Se necesita tipo de cambio cuando un producto tiene una moneda distinta a la cotización. Se conservan los ajustes, descuentos sucesivos y redondeo al entero del cotizador anterior.</p></fieldset>
    <fieldset className="calculator-section" disabled={busy||saved}><legend>{editing===null?"Añadir producto":"Editar producto"}</legend><label>Buscar en el catálogo<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Código o nombre de repuesto / maquinaria"/></label>{(loadingParts||loadingMachines)&&<p>Cargando catálogo…</p>}{(partsError||machinesError)&&<p role="alert">No se pudo cargar todo el catálogo. Puedes completar el producto manualmente.</p>}{!!suggestions.length&&<ul className="calculator-suggestions">{suggestions.map(p=><li key={`${p.tipo}-${p.id}`}><button type="button" onClick={()=>{setItem({...newItem(),code:p.code,desc:p.desc,brand:p.brand,unit:p.unit,product_id:p.id,tipo:p.tipo,brandAdjustments:p.brand.toUpperCase()==="CAT"?[18]:[]});setSearch("");}}>{p.code} · {p.desc}</button></li>)}</ul>}
    <div className="calculator-grid"><label>Código<input type="text" value={item.code} onChange={e=>setItem(p=>({...p,code:e.target.value}))}/></label><label>Marca<input type="text" value={item.brand} onChange={e=>setItem(p=>({...p,brand:e.target.value,brandAdjustments:e.target.value.toUpperCase()==="CAT"?[18]:[]}))}/></label><label>Tipo<select aria-label="Tipo de producto" value={item.tipo} onChange={e=>setItem(p=>({...p,tipo:e.target.value as CalculatorItem['tipo']}))}><option value="repuesto">Repuesto u otro</option><option value="maquinaria">Maquinaria</option></select></label><label>Unidad<input type="text" value={item.unit} onChange={e=>setItem(p=>({...p,unit:e.target.value}))}/></label><label>Cantidad<input type="number" min="1" value={item.qty} onChange={e=>setItem(p=>({...p,qty:Number(e.target.value)}))}/></label><label>Precio original<input type="number" min="0" step="0.01" value={item.price} onChange={e=>setItem(p=>({...p,price:Number(e.target.value)}))}/></label><label>Moneda del precio original<select aria-label="Moneda del precio original" value={item.currency} onChange={e=>setItem(p=>({...p,currency:e.target.value as CalculatorItem['currency']}))}><option value="USD">Dólares (USD)</option><option value="PEN">Soles (PEN)</option></select></label></div>
    <label>Descripción<input type="text" value={item.desc} onChange={e=>setItem(p=>({...p,desc:e.target.value}))}/></label>
    <div className="calculator-grid">{([['brandAdjustments','Ajuste por marca (%)',adjustment,setAdjustment],['discounts','Descuento (%)',discount,setDiscount]] as const).map(([kind,label,value,setValue])=><div key={kind}><label>{label}<div className="calculator-percentage"><input type="number" min="0" max="100" value={value} onChange={e=>setValue(e.target.value)}/><button type="button" className="btn-admin small outline" aria-label={`Añadir ${kind==="discounts"?"descuento":"ajuste"}`} onClick={()=>percentage(kind,value)}><Plus size={16}/></button></div></label><div className="calculator-chips">{item[kind].map((n,i)=><button key={i} type="button" title="Quitar porcentaje" onClick={()=>setItem(p=>({...p,[kind]:p[kind].filter((_,j)=>j!==i)}))}>{kind==="discounts"?"−":"+"}{n}% ×</button>)}</div></div>)}</div><label className="calculator-check"><input type="checkbox" checked={item.showDiscounts} onChange={e=>setItem(p=>({...p,showDiscounts:e.target.checked}))}/>Mostrar descuentos en la descripción del PDF</label><button type="button" className="btn-admin yellow" onClick={add}>{editing===null?"Agregar producto":"Aplicar cambios"}</button>{editing!==null&&<button type="button" className="btn-admin outline" onClick={()=>{setEditing(null);setItem(newItem());}}>Cancelar edición</button>}</fieldset>
    <section className="calculator-section"><h2>Productos de la cotización</h2><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Producto</th><th>Cantidad</th><th>Precio final ({quote.moneda_mostrar})</th><th>Subtotal</th><th>Acciones</th></tr></thead><tbody>{quote.items.map((p,i)=><tr key={i}><td>{p.code} · {p.desc}<small className="calculator-product-detail">{p.brand} · {p.currency} {p.price.toFixed(2)}</small></td><td>{p.qty}</td><td>{Number.isFinite(finalPrice(p,quote))?finalPrice(p,quote).toFixed(2):"Falta tipo de cambio"}</td><td>{Number.isFinite(finalPrice(p,quote))?(finalPrice(p,quote)*p.qty).toFixed(2):"—"}</td><td><button type="button" className="access-icon-action" title="Editar producto" aria-label={`Editar producto ${i+1}`} disabled={busy||saved} onClick={()=>{setItem({...p});setEditing(i);}}><Pencil size={16}/></button> <button type="button" className="access-icon-action danger" title="Quitar producto" aria-label={`Quitar producto ${i+1}`} disabled={busy||saved} onClick={()=>{setQuote(q=>({...q,items:q.items.filter((_,j)=>j!==i)}));if(editing===i){setEditing(null);setItem(newItem());}else if(editing!==null&&editing>i)setEditing(editing-1);}}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div><strong className="calculator-total">Total: {quote.moneda_mostrar} {valid?total.toFixed(2):"Falta tipo de cambio"}</strong></section>
    <section className={`calculator-section calculator-official ${quote.oficial?"enabled":""}`}><label className="calculator-check"><input type="checkbox" role="switch" checked={quote.oficial} disabled={busy||saved} onChange={e=>change("oficial",e.target.checked)}/><strong>Registrar esta cotización como oficial en el panel de control</strong></label><p>{quote.oficial?"Al guardar se registrarán el cliente, los productos, el importe y el PDF. Si viene de una solicitud, quedará vinculada a ella y el cliente podrá ver la respuesta en la página si tiene cuenta.":"Modo de prueba: guardar conserva el documento en el historial, sin crear ni modificar cotizaciones oficiales."}</p></section>
    <div className="calculator-actions"><button className="btn-admin yellow" disabled={busy||saved} onClick={()=>void save()}><Save size={16}/>{busy?"Guardando…":saved?"Guardada":quote.oficial?"Guardar cotización oficial":"Guardar en historial"}</button><button className="btn-admin outline" disabled={!valid} onClick={()=>void download()}><Download size={16}/>Descargar PDF</button><button className="btn-admin outline" disabled={busy} onClick={async()=>{if(await feedback.confirm({title:"Nueva cotización",message:"Los cambios sin guardar se perderán. ¿Continuar?",confirmLabel:"Nueva cotización"})){setQuote(newQuote());setItem(newItem());setEditing(null);setError("");}}}>Nuevo documento</button>{saved&&<Link className="btn-admin outline" to={`/admin/calculadora?historial=${quote.id}`}>Crear una nueva versión</Link>}{quote.cotizacion_id&&<Link to={`/admin/cotizaciones/${quote.cotizacion_id}`}>Ver registro oficial</Link>}</div>
    </div><aside className="calculator-pdf"><h2>Vista previa del PDF</h2>{valid&&pdfUrl?<iframe src={pdfUrl} title="Vista previa PDF de la cotización"/>:<p>Completa el tipo de cambio para ver el PDF.</p>}</aside></div></div>;
}
