import { useEffect, useState, type FormEvent } from 'react';
import { Pencil, Trash2, Plus, ShieldCheck } from 'lucide-react';
import { api } from '../../api/client';
import { useFeedback } from '../../context/FeedbackContext';
export interface PanelRole {clave:string;nombre:string;permisos:string[];sistema:boolean;}
interface RoleData {roles:PanelRole[];secciones:Record<string,string>;reservados:Record<string,string>;}
export default function RolesPanel({onChange}:{onChange:(roles:PanelRole[])=>void}){
 const [data,setData]=useState<RoleData|null>(null);const [editing,setEditing]=useState<string|null>(null);const [name,setName]=useState('');const [grants,setGrants]=useState<string[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const feedback=useFeedback();
 useEffect(()=>{let active=true;api.get<RoleData>('/api/roles').then(d=>{if(active){setData(d);onChange(d.roles);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[onChange]);
 async function reload(){const d=await api.get<RoleData>('/api/roles');setData(d);onChange(d.roles);}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const payload={nombre:name,permisos:grants};if(editing==='nuevo')await api.post('/api/roles',payload);else await api.put(`/api/roles/${editing}`,payload);await reload();setEditing(null);feedback.success('Rol guardado. Sus permisos se aplican a las cuentas asignadas.');}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}}
 async function remove(r:PanelRole){if(!await feedback.confirm({title:'Eliminar rol',message:`¿Eliminar ${r.nombre}? Primero debes reasignar sus usuarios.`,confirmLabel:'Eliminar',danger:true}))return;setBusy(true);try{await api.delete(`/api/roles/${r.clave}`);await reload();}catch(e){setError(e instanceof Error?e.message:'No se pudo eliminar.');}finally{setBusy(false);}}
 return <section className="roles-panel" aria-labelledby="roles-title"><div className="admin-header-row"><div><h2 id="roles-title"><ShieldCheck size={20}/> Roles y sus accesos</h2><p>Elige un rol al crear o editar una cuenta. Los roles personalizados pueden gestionar las secciones seleccionadas.</p></div><button type="button" className="btn-admin outline" aria-label="Crear rol" title="Crea un rol y elige las secciones que podrá gestionar" data-tooltip="Crea un rol y elige las secciones que podrá gestionar" disabled={busy} onClick={()=>{setEditing('nuevo');setName('');setGrants([]);setError('');}}><Plus size={16}/>Crear rol</button></div>{error&&<p className="admin-error" role="alert">{error}</p>}
 {editing&&<form className="admin-form role-editor" onSubmit={save}><h3>{editing==='nuevo'?'Nuevo rol':'Editar rol'}</h3><label>Nombre del rol<input required maxLength={80} value={name} placeholder="Por ejemplo: Editor de contenido" onChange={e=>setName(e.target.value)}/></label><p>Marca las secciones que esta persona podrá abrir y gestionar. Excel requiere además el acceso a la sección que se va a importar o exportar. La calculadora requiere Cotizaciones de repuestos para registrar documentos oficiales.</p><div className="role-permissions">{Object.entries(data?.secciones??{}).map(([key,label])=><label className="role-permission" key={key}><input type="checkbox" checked={grants.includes(key)} onChange={e=>setGrants(g=>e.target.checked?[...g,key]:g.filter(p=>p!==key))}/><span>{label}</span></label>)}</div><p className="role-owner-note">Exclusivos del owner: cotizaciones de maquinaria, administrar accesos y roles, números y correo, auditoría y papelera.</p><div className="admin-form-actions"><button className="btn-admin yellow" disabled={busy||!grants.length}>{busy?'Guardando…':'Guardar rol'}</button><button type="button" className="btn-admin outline" disabled={busy} onClick={()=>setEditing(null)}>Cancelar</button></div></form>}
 {!data?<p>Cargando roles…</p>:<div className="roles-grid">{data.roles.map(r=><article className="role-card" key={r.clave}><div className="role-card-heading"><h3>{r.nombre}</h3><span className="role-kind">{r.sistema?'Del sistema':'Personalizado'}</span></div><div className="role-tags">{r.permisos.length?r.permisos.map(p=><span key={p}>{r.clave==="cotizador"&&p==="excel"?"Excel · solo descargar":data.secciones[p]??data.reservados[p]??p}</span>):<p>Cuenta de cliente: sin acceso al panel.</p>}</div>{!r.sistema&&<div className="role-card-actions"><button type="button" className="access-icon-action" aria-label={`Editar rol ${r.nombre}`} title="Cambiar el nombre o las secciones de este rol" data-tooltip="Cambiar el nombre o las secciones de este rol" disabled={busy} onClick={()=>{setEditing(r.clave);setName(r.nombre);setGrants(r.permisos);setError('');}}><Pencil size={16}/></button><button type="button" className="access-icon-action danger" aria-label={`Eliminar rol ${r.nombre}`} title="Eliminar el rol si no tiene usuarios asignados" data-tooltip="Eliminar el rol si no tiene usuarios asignados" disabled={busy} onClick={()=>void remove(r)}><Trash2 size={16}/></button></div>}</article>)}</div>}</section>;
}
